version: 1.{build}

clone_folder: c:\projects\cglm
os: Visual Studio 2015
platform: x64

before_build:
    - echo Running cmake...
    - cd c:\projects\cglm
    - cmake -G "Visual Studio 14 2015 Win64"

build:
    project: INSTALL.vcxproj
